FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
ARG DIRECT_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/docs ./apps/docs

RUN bun install
RUN bun run prisma:generate
RUN DATABASE_URL=${DATABASE_URL} DIRECT_URL=${DIRECT_URL} bun run build:frontend

EXPOSE 3000

CMD ["bun","run","start:frontend"]